import { RecoilRoot } from 'recoil';
import Head from 'next/head';
import { Layout } from '../components/Layout';
import { isMobile } from 'react-device-detect';

import '../../styles/globals.css';
import { SoundsProvider, useSoundsContext } from '../context/SoundsContext';

function MyApp({ Component, pageProps }) {
  return (
    <RecoilRoot>
      <SoundsProvider>
        <Layout>
          <Head>
            <title>dorta.dev - creative developer.</title>
            <meta name='description' content='Generated by create next app' />
          </Head>

          <Component {...pageProps} />
        </Layout>
      </SoundsProvider>
    </RecoilRoot>
  );
}

export default MyApp;
