import Head from 'next/head';
import Layout from '../components/Layout';
import '../styles/globals.css';

function MyApp({ Component, pageProps }) {
  return (
    <Layout>
      <Head>
        {/* <title>&#123;dorta.dev&#125;</title> */}
        <title>dorta.dev, creative developer.</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Component {...pageProps} />
    </Layout>
  );
}

export default MyApp;
