import Head from 'next/head';
import Layout from '../components/Layout.tsx';
import { Navbar } from '../components/Navbar.tsx';

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Dorta.dev - Creative developer</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <Navbar />
    </Layout>
  );
}
